export const stubbedResponse = {
  weekDays: [
    {
      id: "1",
      title: "Monday",
      tempMax: "44",
      tempMin: "24",
      cloudDenses: "",
      desc: "Thunderstorm",
      rangeId: 210,
    },
    {
      id: "2",
      title: "Tuesday",
      tempMax: "43",
      tempMin: "23",
      cloudDenses: "low",
      desc: "Drizzle",
      rangeId: 315,
    },
    {
      id: "3",
      title: "Wednesday",
      tempMax: "42",
      tempMin: "22",
      cloudDenses: "",
      desc: "Rain",
      rangeId: 520,
    },
    {
      id: "4",
      title: "Thursday",
      tempMax: "41",
      tempMin: "21",
      cloudDenses: "",
      desc: "Snow",
      rangeId: 612,
    },
    {
      id: "5",
      title: "Friday",
      tempMax: "39",
      tempMin: "19",
      cloudDenses: "",
      desc: "Atmosphere",
      rangeId: 750,
    },
    {
      id: "6",
      title: "Saturday",
      tempMax: "38",
      tempMin: "18",
      cloudDenses: "heavy",
      desc: "Clear Sky",
      thunderStorm: true,
      rangeId: 800,
    },
    {
      id: "7",
      title: "Sunday",
      tempMax: "37",
      tempMin: "17",
      cloudDenses: "",
      desc: "Clouds",
      rangeId: 802,
    },
  ],
};
