export const stubbedResponse = {
  weekDays: [
    {
      id: "1",
      title: "Monday",
      max: "30",
      min: "20",
      cloudDenses: "",
      canBeRain: false,
    },
    {
      id: "2",
      title: "Tuesday",
      max: "30",
      min: "20",
      cloudDenses: "low",
      canBeRain: true,
    },
    {
      id: "3",
      title: "Wednesday",
      max: "30",
      min: "20",
      cloudDenses: "",
      canBeRain: false,
    },
    {
      id: "4",
      title: "Thursday",
      max: "30",
      min: "20",
      cloudDenses: "",
      canBeRain: false,
    },
    {
      id: "5",
      title: "Friday",
      max: "30",
      min: "20",
      cloudDenses: "",
      canBeRain: false,
    },
    {
      id: "6",
      title: "Saturday",
      max: "30",
      min: "20",
      cloudDenses: "heavy",
      canBeRain: true,
      thunderStorm: true,
    },
    {
      id: "7",
      title: "Sunday",
      max: "30",
      min: "20",
      cloudDenses: "",
      canBeRain: true,
    },
  ],
};
