export const stubbedResponse = {
  weekDays: [
    {
      id: "1",
      title: "Monday",
      tempMax: "44",
      tempMin: "24",
      cloudDenses: "",
      canBeRain: false,
      rangeId: 301,
    },
    {
      id: "2",
      title: "Tuesday",
      tempMax: "43",
      tempMin: "23",
      cloudDenses: "low",
      canBeRain: true,
      rangeId: 401,
    },
    {
      id: "3",
      title: "Wednesday",
      tempMax: "42",
      tempMin: "22",
      cloudDenses: "",
      canBeRain: false,
      rangeId: 500,
    },
    {
      id: "4",
      title: "Thursday",
      tempMax: "41",
      tempMin: "21",
      cloudDenses: "",
      canBeRain: false,
      rangeId: 135,
    },
    {
      id: "5",
      title: "Friday",
      tempMax: "39",
      tempMin: "19",
      cloudDenses: "",
      canBeRain: false,
      rangeId: 444,
    },
    {
      id: "6",
      title: "Saturday",
      tempMax: "38",
      tempMin: "18",
      cloudDenses: "heavy",
      canBeRain: true,
      thunderStorm: true,
      rangeId: 202,
    },
    {
      id: "7",
      title: "Sunday",
      tempMax: "37",
      tempMin: "17",
      cloudDenses: "",
      canBeRain: true,
      rangeId: 501,
    },
  ],
};
